name: Main Build

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
    branches: [master]
    paths-ignore: ['**.md']

env:
  IMAGE_NAME: getnova/nova-backend
  DOCKER_PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run checks with Gradle
        run: ./gradlew check --no-daemon

  #  bintary:
  #    needs: check
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - uses: actions/checkout@v2
  #
  #      - uses: actions/cache@v1
  #        with:
  #          path: ~/.gradle/caches
  #          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
  #          restore-keys: |
  #            ${{ runner.os }}-gradle-
  #
  #      - name: Set up JDK 14
  #        uses: actions/setup-java@v1
  #        with:
  #          java-version: 14
  #
  #      - name: Grant execute permission for gradlew
  #        run: chmod +x gradlew
  #
  #      - name: Upload with Gradle
  #        run: ./gradlew bintrayUpload --no-daemon
  #        env:
  #          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
  #          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}

  build:
    needs: check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew installDist --no-daemon

      - uses: actions/upload-artifact@v2
        with:
          name: nova-backend
          path: nova-bootstrap/build/install/nova-bootstrap

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download artefacts
        uses: actions/download-artifact@v1
        with:
          name: nova-backend

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create Version
        id: prepare
        run: |
          VERSION=edge

          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi

          TAGS="--tag $IMAGE_NAME:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS --tag $IMAGE_NAME:latest"
          fi

          echo ::set-output name=version::$VERSION
          echo ::set-output name=buildx_args::--platform $DOCKER_PLATFORMS \
            ${TAGS} --file ./docker/Dockerfile.github-actions ./

      - name: Docker Buildx (build)
        run: docker buildx build --output "type=image,push=false" ${{ steps.prepare.outputs.buildx_args }}

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker Buildx (push)
        run: docker buildx build --output "type=image,push=true" ${{ steps.prepare.outputs.buildx_args }}

      - name: Docker Check Manifest
        run: docker run --rm mplatform/mquery $IMAGE_NAME:${{ steps.prepare.outputs.version }}

      - name: Clear
        if: always()
        run: rm -f ${HOME}/.docker/config.json
